(#1) Add support for Github login
GeeksCAT/anem-per-feina pull request #124
Opened 2020-10-25 12:39 UTC by oriolpiera

## Description

Fix: https://github.com/GeeksCAT/anem-per-feina/issues/1

This PR adds a new feature, login with your Github account.

![image](https://user-images.githubusercontent.com/26488435/97107349-511ba000-16c7-11eb-9e96-d73a057b5f67.png)

## Code formating

The code has to be well formatted following the formatting rules. For example in Python the code has to follow the PEP8.

Before create your PR, please make sure your code is well formatted and styled doing:
```bash
$ >> pre-commit run --all
```

2020-10-25 21:00 UTC, jbagot requested changes

2020-10-25 21:00 UTC, jbagot commented on .env.dev.sample
> +SOCIAL_AUTH_GITHUB_KEY=githubt-key
If they are not mandatory I wouldn't add them here

2020-10-26 07:13 UTC, oriolpiera commented on jobs/settings.py
> +    "constance.backends.database",
done

2020-10-26 07:13 UTC, oriolpiera commented on requirements.txt
> +celery==5.0.1
done

2020-10-26 07:14 UTC, oriolpiera commented on .env.dev.sample
> +SOCIAL_AUTH_GITHUB_KEY=githubt-key
removed, done.

2020-10-26 15:50 UTC, francescarpi approved these changes

2020-10-26 15:50 UTC, francescarpi commented
Nice job!

2020-10-27 13:09 UTC, merged