(#37) [Improvement]: sqlite database removed from repository
GeeksCAT/anem-per-feina pull request #57
Opened 2020-10-10 15:37 UTC by francescarpi

## Description

Fix  #37 

This PR remove sqlite database from repository, add demo fixtures and update documentation explain how to use them.

## Code formating

The code has to be well formatted following the formatting rules. For example in Python the code has to follow the PEP8.

2020-10-10 15:37 UTC, francescarpi commented
I keep it in draft mode waiting #51 be deployed.

2020-10-10 21:32 UTC, jbagot requested changes

2020-10-10 21:32 UTC, jbagot commented on .env.dev.sample
> +DEBUG=on
DEBUG=True

2020-10-10 21:35 UTC, francescarpi commented on .env.dev.sample
> +DEBUG=on
Ok, I'll change it tomorrow.
Thanks!

2020-10-10 23:28 UTC, XaviTorello requested changes
Thanks @francescarpi once DEBUG boolean is fixed this will be fine :)

The sqlite vs db extension is not a core decision, so it's up to you :)

2020-10-10 23:28 UTC, XaviTorello commented on .env.dev.sample
> +DATABASE_URL=sqlite:///anem-per-feina.db
Maybe it's more clear if we preserve the `.sqlite` extension. I know that `.db` also is normally interpreted as sqlite, but maybe it's simpler and avoids misunderstandings 🤷🏻‍♂

2020-10-11 08:12 UTC, francescarpi commented
Hi!
I did it based on the official documentation

https://django-environ.readthedocs.io/en/latest/

But its more cleared now, with your proposals.

Changes done!
Thanks!

2020-10-11 21:31 UTC, XaviTorello approved these changes
Looks good, many thanks @francescarpi  :beers:

2020-10-13 10:19 UTC, fullonic commented on jobs/settings/__init__.py
>      #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
@francescarpi We can also remove this commented code about postgres database.

2020-10-13 12:14 UTC, merged