Improve README file
GeeksCAT/anem-per-feina pull request #95
Opened 2020-10-15 13:49 UTC by victormartingarcia

## Description

Fix: #58 

Changes on README.md for better communicating what this project is, and provide some guidance to incentivize contribution

## Code formating

Only affects README.md

2020-10-17 08:12 UTC, XaviTorello requested changes
I love it @victormartingarcia, just minor list numeration change

Please, fix conflicts adding `make` references and will be merged :)

2020-10-17 08:12 UTC, XaviTorello commented on README.md
> +**Anem per feina** is an open source project promoted by [GeeksCat](https://geekscat.org/) association for [Hactoberfest 2020](https://hacktoberfest.geekscat.org/) event.
F*ck yeah!

2020-10-17 08:12 UTC, XaviTorello commented on README.md
> +**Anem per feina** is a collaborative effort where everybody is more than welcome to contribute, no experience is required!
😍😍😍

2020-10-17 08:12 UTC, XaviTorello commented on README.md
>  3. Restart development containers with `docker-compose up`
Should be 2

2020-10-17 08:12 UTC, XaviTorello commented on README.md
> +## Tech stack
💪💪💪

2020-10-17 15:17 UTC, jbagot commented
I like it, for me it's approved when you will fix the comments of Xavi. Great work :) It's a fancier README

2020-10-18 06:14 UTC, victormartingarcia commented on README.md
>  3. Restart development containers with `docker-compose up`
Nice catch! Already fixed

2020-10-18 06:15 UTC, victormartingarcia commented
> I love it @victormartingarcia, just minor list numeration change
> 
> Please, fix conflicts adding `make` references and will be merged :)

Fixed conflicts 👍

2020-10-18 06:17 UTC, XaviTorello approved these changes
💪

2020-10-18 09:11 UTC, merged